/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.C_employee;
import Control.Lists_Meun;

import Control.c_families_members;
import Control.generalcontrol;
import Model.Model_Tables;
import Model.general_Model;
import Model.m_families_members;

import Model.m_registerno;
import Model.m_registerplace;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author ahmad-soft
 */
public class families_members extends javax.swing.JDialog {
    
    Control.C_employee model_employess;
    Control.c_families_members control_family;
    Model.m_families_members model_family;
    
    public families_members(java.awt.Frame parent, boolean moda) {
        super(parent, moda);
        initComponents();
        calerTools();
        model_employess = new C_employee();
        control_family = new c_families_members();
        model_family = new m_families_members();
        full_names_id_emploees();
        full_social_status();
        loadcombobox();
        
        //  cmb_district.setModel(new DefaultComboBoxModel(new Integer[0]));
//        fullcombobox_district();
//        fullcombobox_registerplace();
//        txt_id.setVisible(false);
//    

    }
//    Model.general_Model m = new general_Model();
//    Control.generalcontrol c = new generalcontrol();
//

    public void full_names_id_emploees() {
        ArrayList<Model.M_Add_employee> ac = new ArrayList<>();
        Control.C_employee ad = new C_employee();
        ac = ad.view_namesand_idemployees();
        DefaultComboBoxModel model = (DefaultComboBoxModel) comb_names_emps.getModel();
        model.removeAllElements();
        model.addAll(ac);
    }
    
    public void full_social_status() {
        Lists_Meun.Array_c_social_status = Lists_Meun.c_social_status.filltable("social_status");
        DefaultComboBoxModel model = (DefaultComboBoxModel) com_social_status.getModel();
        model.removeAllElements();
        model.addAll(Lists_Meun.Array_c_social_status);
    }
    
    public void loadcombobox() {
        com_member_relation.setModel(new DefaultComboBoxModel<>(Model.type_relation_enum.values()));
    }
    
    
    
    public void calerTools(){
        txt_member.setText("");
        check_Exist.setSelected(false);
        check_emp.setSelected(false);
        check_studey.setSelected(false);
        com_social_status.setSelectedIndex(-1);
        member_brith_date.setDate(null);
        com_member_relation.setSelectedIndex(-1);
    }

//    public void fullcombobox_registerplace() {
//   
//     int id_district = ((Model_Tables) cmb_district.getSelectedItem()).getColumn_Id();
//
//        Control.c_registerplace a = new Control.c_registerplace();
//        Model.m_registerplace b = new Model.m_registerplace();
//        ArrayList<m_registerplace> cc = a.view_registerplace(id_district);
//  //      DefaultComboBoxModel  model1 = (DefaultComboBoxModel) cmb_registerplace.getModel();
//      //  model1.removeAllElements();
//       // model1.addAll(cc);
//       cmb_registerplace.setModel(new DefaultComboBoxModel(cc.toArray()));
//    }
//
//    public void full_registerno() {
//        int id_district = ((Model_Tables) cmb_district.getSelectedItem()).getColumn_Id();
//        int id_registerplace = ((m_registerplace) cmb_registerplace.getSelectedItem()).getId();
//
//        Control.c_registerno a = new Control.c_registerno();
//        Model.m_registerno b = new Model.m_registerno();
//        ArrayList<m_registerno> cc = a.view_registeno(id_district, id_registerplace);
//
//        DefaultTableModel modle = new DefaultTableModel(){@Override
//        public boolean isCellEditable(int row, int column){
//            return false;
//        }
//        };
//        modle.setColumnIdentifiers(new Object[]{"اسم", "رقم"});
//        Object[] row = new Object[2];
//        for (int i = 0; i < cc.size(); i++) {
//            row[0] = cc.get(i).getName();
//            row[1] = cc.get(i).getId();
//            modle.addRow(row);
//        }
//        tableDirect.setModel(modle);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_registerplace = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p3 = new javax.swing.JLabel();
        N_type_of_doc_p1 = new javax.swing.JLabel();
        N_type_of_doc_p = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnl1 = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        btn_previous = new RSMaterialComponent.RSButtonMaterialShadow();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDirect = new rojerusan.RSTableMetro();
        lbl_name = new javax.swing.JLabel();
        txt_name = new RSMaterialComponent.RSTextFieldMaterial();
        btn_add1 = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_update = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_del = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_Exit = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id = new javax.swing.JTextField();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();
        N_type_of_doc_p2 = new javax.swing.JLabel();
        comb_names_emps = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel17 = new javax.swing.JLabel();
        member_brith_date = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        check_Exist = new RSMaterialComponent.RSCheckBoxMaterial();
        check_emp = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        check_studey = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_Exit1 = new RSMaterialComponent.RSButtonMaterialShadow();
        N_type_of_doc_p4 = new javax.swing.JLabel();
        com_member_relation = new RSMaterialComponent.RSComboBoxMaterial<>();
        txt_member = new RSMaterialComponent.RSTextFieldMaterial();
        N_place3 = new javax.swing.JLabel();
        N_type_of_doc_p5 = new javax.swing.JLabel();
        com_social_status = new RSMaterialComponent.RSComboBoxMaterial();

        cmb_registerplace.setBackground(new java.awt.Color(254, 254, 254));
        cmb_registerplace.setForeground(new java.awt.Color(1, 1, 1));
        cmb_registerplace.setToolTipText("");
        cmb_registerplace.setColorMaterial(new java.awt.Color(185, 146, 79));
        cmb_registerplace.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmb_registerplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_registerplaceActionPerformed(evt);
            }
        });

        N_type_of_doc_p3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p3.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p3.setText("اسم مكان قيد");

        N_type_of_doc_p1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        N_type_of_doc_p1.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p1.setText("الرجاء اختيار مكان القيد لإضافة رقم قيد لها");

        N_type_of_doc_p.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        N_type_of_doc_p.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p.setText("الرجاء اختيار الأمانة لإضافة رقم قيد لها");

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(254, 254, 254));
        pnl1.setName("pnl1"); // NOI18N
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rSPanelsSlider1.add(pnl1, "card2");

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setName("pnl2"); // NOI18N
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_previous.setBackground(new java.awt.Color(185, 146, 79));
        btn_previous.setText("سابق");
        btn_previous.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_previous.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_previous.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_previous.setEffectFocus(true);
        btn_previous.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previousActionPerformed(evt);
            }
        });
        pnl2.add(btn_previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 67, 41));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setText("واجهة رقم القيد");
        pnl2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        tableDirect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الاسم حالة الإجتماعية", "الرقم حالة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDirect.setColorBackgoundHead(new java.awt.Color(185, 146, 79));
        tableDirect.setColorFilasBackgound2(new java.awt.Color(71, 60, 42));
        tableDirect.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tableDirect.setColorFilasForeground2(new java.awt.Color(253, 251, 251));
        tableDirect.setColorSelBackgound(new java.awt.Color(185, 146, 79));
        tableDirect.setFont(new java.awt.Font("Arial CE", 1, 15)); // NOI18N
        tableDirect.setFuenteFilas(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteHead(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tableDirect.setRowHeight(20);
        tableDirect.getTableHeader().setResizingAllowed(false);
        tableDirect.getTableHeader().setReorderingAllowed(false);
        tableDirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDirectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDirect);

        pnl2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 357, 239));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name.setText("رقم قيد");
        pnl2.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        txt_name.setForeground(new java.awt.Color(1, 1, 1));
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name.setPlaceholder("");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        pnl2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, -1));

        btn_add1.setBackground(new java.awt.Color(185, 146, 79));
        btn_add1.setText("اضافة");
        btn_add1.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add1.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add1.setEffectFocus(true);
        btn_add1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        pnl2.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 65, 41));

        btn_update.setBackground(new java.awt.Color(185, 146, 79));
        btn_update.setText("تعديل");
        btn_update.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_update.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_update.setEffectFocus(true);
        btn_update.setEnabled(false);
        btn_update.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        pnl2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 67, 41));

        btn_del.setBackground(new java.awt.Color(185, 146, 79));
        btn_del.setText("حذف");
        btn_del.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_del.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_del.setEffectFocus(true);
        btn_del.setEnabled(false);
        btn_del.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        pnl2.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 67, 41));

        btn_Exit.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit.setText("خروج");
        btn_Exit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit.setEffectFocus(true);
        btn_Exit.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        pnl2.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 67, 41));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        pnl2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, 20, -1));

        rSPanelsSlider1.add(pnl2, "card3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);

        rSPanelMaterial1.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 1, 1), 2, true));
        rSPanelMaterial1.setBgShade(new java.awt.Color(1, 1, 1));

        rSPanelMaterial2.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 146, 79), 2));
        rSPanelMaterial2.setForeground(new java.awt.Color(1, 1, 1));
        rSPanelMaterial2.setBgShade(new java.awt.Color(185, 146, 79));

        N_type_of_doc_p2.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        N_type_of_doc_p2.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p2.setText(" اسم الموظف");

        comb_names_emps.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps.setToolTipText("");
        comb_names_emps.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_empsActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 1, 1));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("تاريخ الولادة");

        member_brith_date.setBackground(new java.awt.Color(250, 252, 255));
        member_brith_date.setBorder(null);
        member_brith_date.setDateFormatString("dd-MM-yyyy");

        jLabel15.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(1, 1, 1));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("موجود او غير موجود");

        check_Exist.setForeground(new java.awt.Color(1, 1, 1));
        check_Exist.setText("موجود");
        check_Exist.setColorCheck(new java.awt.Color(185, 146, 79));
        check_Exist.setColorUnCheck(new java.awt.Color(1, 1, 1));
        check_Exist.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        check_Exist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check_Exist.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        check_Exist.setIsEffectRipple(false);

        check_emp.setForeground(new java.awt.Color(1, 1, 1));
        check_emp.setText("موظف");
        check_emp.setColorCheck(new java.awt.Color(185, 146, 79));
        check_emp.setColorUnCheck(new java.awt.Color(1, 1, 1));
        check_emp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        check_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check_emp.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        check_emp.setIsEffectRipple(false);

        jLabel18.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(1, 1, 1));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("موظف أو غير موظف");

        jLabel20.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 1, 1));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("يدرس أو لا يدرس");

        check_studey.setForeground(new java.awt.Color(1, 1, 1));
        check_studey.setText("يدرس");
        check_studey.setColorCheck(new java.awt.Color(185, 146, 79));
        check_studey.setColorUnCheck(new java.awt.Color(1, 1, 1));
        check_studey.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        check_studey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check_studey.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        check_studey.setIsEffectRipple(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setText("بيانات عائلة");

        btn_add.setBackground(new java.awt.Color(185, 146, 79));
        btn_add.setText("أضافة");
        btn_add.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add.setEffectFocus(true);
        btn_add.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_Exit1.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit1.setText("خروج");
        btn_Exit1.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit1.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit1.setEffectFocus(true);
        btn_Exit1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit1ActionPerformed(evt);
            }
        });

        N_type_of_doc_p4.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        N_type_of_doc_p4.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p4.setText("نوع العلاقة");

        com_member_relation.setBackground(new java.awt.Color(254, 254, 254));
        com_member_relation.setForeground(new java.awt.Color(1, 1, 1));
        com_member_relation.setToolTipText("");
        com_member_relation.setColorMaterial(new java.awt.Color(185, 146, 79));
        com_member_relation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        com_member_relation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_member_relationActionPerformed(evt);
            }
        });

        txt_member.setForeground(new java.awt.Color(1, 1, 1));
        txt_member.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_member.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_member.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_member.setPlaceholder("");
        txt_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_memberActionPerformed(evt);
            }
        });
        txt_member.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_memberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_memberKeyTyped(evt);
            }
        });

        N_place3.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        N_place3.setForeground(new java.awt.Color(7, 2, 2));
        N_place3.setText("اسم العضو");

        N_type_of_doc_p5.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        N_type_of_doc_p5.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p5.setText("حالة الاجتماعية");

        com_social_status.setBackground(new java.awt.Color(254, 254, 254));
        com_social_status.setForeground(new java.awt.Color(1, 1, 1));
        com_social_status.setToolTipText("");
        com_social_status.setColorMaterial(new java.awt.Color(185, 146, 79));
        com_social_status.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        com_social_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_social_statusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial2Layout = new javax.swing.GroupLayout(rSPanelMaterial2);
        rSPanelMaterial2.setLayout(rSPanelMaterial2Layout);
        rSPanelMaterial2Layout.setHorizontalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(comb_names_emps, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(member_brith_date, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com_member_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_Exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_studey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N_type_of_doc_p2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_place3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(N_type_of_doc_p5)
                                .addComponent(jLabel20))))
                    .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel2))
                    .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(com_social_status, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        rSPanelMaterial2Layout.setVerticalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p2))
                .addGap(10, 10, 10)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_place3))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(member_brith_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(15, 15, 15)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(com_member_relation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p4))
                .addGap(10, 10, 10)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_Exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(10, 10, 10)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_studey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(com_social_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comb_names_empsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_empsActionPerformed
        

    }//GEN-LAST:event_comb_names_empsActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
//            if (txt_name.getText().equals("")) {
//                new rojerusan.RSNotifyAnimated("معلومات", "الرجاء عم ترك مربع فارغ", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
//                return;
//            }
            int id_emp = ((Model.M_Add_employee) comb_names_emps.getSelectedItem()).getId_emp();
            Model.Model_Tables id_social = (Model_Tables) com_social_status.getSelectedItem();
            
            model_family.setId_employee_p(id_emp);
            model_family.setMember_name_p(txt_member.getText());
            model_family.setBrith_date_p( member_brith_date.getDate());
            model_family.setType_relation_p(com_member_relation.getSelectedItem().toString());
            model_family.setIs_exist_p(check_Exist.isSelected());
            model_family.setIs_employee_p(check_emp.isSelected());
            model_family.setStudy_p(check_studey.isSelected());
            model_family.setId_social_status_p(Integer.valueOf(id_social.getColumn_Id()));
            
            boolean i = control_family.add(model_family);
            if (i == true) {
     calerTools();
                new rojerusan.RSNotifyAnimated("معلومات", "تم اضافة بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
  
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in   families_members (add) go in btnAdd" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_Exit1ActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_previousActionPerformed

    private void tableDirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDirectMouseClicked
//        int i = (int) tableDirect.getValueAt(tableDirect.getSelectedRow(), 1);
//        String s = (String) tableDirect.getValueAt(tableDirect.getSelectedRow(), 0);
//txt_id.setText(String.valueOf(i));
//        txt_name.setText(s);
//        btn_del.setEnabled(true);
//        btn_update.setEnabled(true);
    }//GEN-LAST:event_tableDirectMouseClicked

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed

    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
//        try {
//
//            if (txt_name.getText() != null && txt_id.getText().equals("")) {
//                new rojerusan.RSNotifyAnimated("معلومات", "الرجاء اختار الاسم  للتعديل عليها", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
//                return;
//            }
//        
//            m.setId(Integer.valueOf(txt_id.getText()));
//            
//             int district = ((Model.Model_Tables) cmb_district.getSelectedItem()).getColumn_Id();
//            int registerplace = ((Model.m_registerplace) cmb_registerplace.getSelectedItem()).getId();
//            m.setTalbe_name("registerno");
//            m.setName_column3("name");
//            m.setName_column2("registerplace_id");
//            m.setName_column1("district_id");
//            m.setValue3(txt_name.getText());
//            m.setValue2(String.valueOf(registerplace));
//            m.setValue1(String.valueOf(district));
//           c.update1(m);
//    full_registerno();
//            btn_del.setEnabled(false);
//            btn_update.setEnabled(false);
//            new rojerusan.RSNotifyAnimated("معلومات", "تم تعديل بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
//            txt_name.setText("");
//            txt_id.setText("");
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Error  go -> btnUpdateMouseClicked in vDirectorate" + ex.getMessage());
//        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
//        try {
//            if (txt_name.getText() != null && txt_id.getText().equals("")) {
//                new rojerusan.RSNotifyAnimated("معلومات", "الرجاء اختار الاسم  للحذف عليها", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
//                return;
//            }
//            m.setId(Integer.valueOf(txt_id.getText()));
//            c.delete(m, "registerno");
//           full_registerno();
//            btn_del.setEnabled(false);
//            btn_update.setEnabled(false);
//            new rojerusan.RSNotifyAnimated("معلومات", "تم حذف بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
//            txt_name.setText("");
//            txt_id.setText("");
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Error  go -> btnDeleteMouseClicked in M_Ministry" + ex.getMessage());
//        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void cmb_registerplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_registerplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_registerplaceActionPerformed

    private void com_member_relationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_member_relationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_member_relationActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_memberActionPerformed

    }//GEN-LAST:event_txt_memberActionPerformed

    private void txt_memberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_memberKeyPressed

    }//GEN-LAST:event_txt_memberKeyPressed

    private void txt_memberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_memberKeyTyped

    }//GEN-LAST:event_txt_memberKeyTyped

    private void com_social_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_social_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_social_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" cmb_districtook and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(families_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(families_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(families_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(families_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new families_members().setVisible(true);
                families_members dialog = new families_members(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N_place3;
    private javax.swing.JLabel N_type_of_doc_p;
    private javax.swing.JLabel N_type_of_doc_p1;
    private javax.swing.JLabel N_type_of_doc_p2;
    private javax.swing.JLabel N_type_of_doc_p3;
    private javax.swing.JLabel N_type_of_doc_p4;
    private javax.swing.JLabel N_type_of_doc_p5;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit1;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add1;
    private RSMaterialComponent.RSButtonMaterialShadow btn_del;
    private RSMaterialComponent.RSButtonMaterialShadow btn_previous;
    private RSMaterialComponent.RSButtonMaterialShadow btn_update;
    private RSMaterialComponent.RSCheckBoxMaterial check_Exist;
    private RSMaterialComponent.RSCheckBoxMaterial check_emp;
    private RSMaterialComponent.RSCheckBoxMaterial check_studey;
    private RSMaterialComponent.RSComboBoxMaterial cmb_registerplace;
    private RSMaterialComponent.RSComboBoxMaterial<Model.type_relation_enum> com_member_relation;
    private RSMaterialComponent.RSComboBoxMaterial com_social_status;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_name;
    private com.toedter.calendar.JDateChooser member_brith_date;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSTableMetro tableDirect;
    private javax.swing.JTextField txt_id;
    public RSMaterialComponent.RSTextFieldMaterial txt_member;
    private RSMaterialComponent.RSTextFieldMaterial txt_name;
    // End of variables declaration//GEN-END:variables
}
