/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Funiction_Tables;
import Model.MessageType;
import Model.Model_Tables;
import Model.getall;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author ahmad-soft
 */
public class Frame_Tables extends javax.swing.JFrame {

    /**
     * Creates new form JFrame2
     */
    public Frame_Tables() {
        initComponents();
        txt_Name.requestFocus();
        filltable();
        txt_Id.setVisible(false);
        lbl_Name1.setVisible(false);
    }

    public Frame_Tables(String name, String name2, String title) {
        initComponents();
        txt_Name.requestFocus();
        lbl_Name.setText(name);
        lbl_title.setText(title);
        this.nameTable = name2;
        filltable();
        txt_Id.setVisible(false);
        lbl_Name1.setVisible(false);

    }
    String nameLable;
    String nameTable;
    boolean row_is_select = false;
    int index;
    getall model;
    Control.Funiction_Tables Conter_tables;

    public void filltable() {
        Conter_tables = new Funiction_Tables();
        ArrayList<Model_Tables> a = Conter_tables.filltable(nameTable);
        Model.getall n = new getall(a);
        tableDirect.setModel(n);
    }

    public void Disabled_btn() {
        btnDel1.setEnabled(false);
        btnUpdate1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new RSMaterialComponent.RSButtonMaterialShadow();
        lbl_Name = new javax.swing.JLabel();
        lbl_Name1 = new javax.swing.JLabel();
        txt_Id = new RSMaterialComponent.RSTextFieldMaterial();
        txt_Name = new RSMaterialComponent.RSTextFieldMaterial();
        btnUpdate1 = new RSMaterialComponent.RSButtonMaterialShadow();
        btnDel1 = new RSMaterialComponent.RSButtonMaterialShadow();
        btnExit1 = new RSMaterialComponent.RSButtonMaterialShadow();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDirect = new rojerusan.RSTableMetro();
        lbl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        btnAdd.setBackground(new java.awt.Color(185, 146, 79));
        btnAdd.setForeground(new java.awt.Color(1, 1, 1));
        btnAdd.setText("اضافة");
        btnAdd.setBackgroundHover(new java.awt.Color(185, 146, 79));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdd.setForegroundText(new java.awt.Color(7, 7, 7));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lbl_Name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(7, 2, 2));
        lbl_Name.setText("الاسم موظف");

        lbl_Name1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Name1.setForeground(new java.awt.Color(7, 2, 2));
        lbl_Name1.setText("رقم ");

        txt_Id.setForeground(new java.awt.Color(1, 1, 1));
        txt_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Id.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_Id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Id.setPlaceholder("");
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });

        txt_Name.setForeground(new java.awt.Color(1, 1, 1));
        txt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_Name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Name.setPlaceholder("");
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });

        btnUpdate1.setBackground(new java.awt.Color(185, 146, 79));
        btnUpdate1.setForeground(new java.awt.Color(1, 1, 1));
        btnUpdate1.setText("تعديل");
        btnUpdate1.setBackgroundHover(new java.awt.Color(185, 146, 79));
        btnUpdate1.setEnabled(false);
        btnUpdate1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdate1.setForegroundText(new java.awt.Color(1, 1, 1));
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnDel1.setBackground(new java.awt.Color(185, 146, 79));
        btnDel1.setForeground(new java.awt.Color(1, 1, 1));
        btnDel1.setText("حذف");
        btnDel1.setBackgroundHover(new java.awt.Color(185, 146, 79));
        btnDel1.setEnabled(false);
        btnDel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDel1.setForegroundText(new java.awt.Color(1, 1, 1));
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });

        btnExit1.setBackground(new java.awt.Color(185, 146, 79));
        btnExit1.setForeground(new java.awt.Color(1, 1, 1));
        btnExit1.setText("خروج");
        btnExit1.setBackgroundHover(new java.awt.Color(185, 146, 79));
        btnExit1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit1.setForegroundText(new java.awt.Color(1, 1, 1));
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        tableDirect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الاسم حالة الإجتماعية", "الرقم حالة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDirect.setColorBackgoundHead(new java.awt.Color(185, 146, 79));
        tableDirect.setColorFilasBackgound2(new java.awt.Color(71, 60, 42));
        tableDirect.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tableDirect.setColorFilasForeground2(new java.awt.Color(253, 251, 251));
        tableDirect.setColorSelBackgound(new java.awt.Color(185, 146, 79));
        tableDirect.setFont(new java.awt.Font("Arial CE", 1, 15)); // NOI18N
        tableDirect.setFuenteFilas(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteHead(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tableDirect.setRowHeight(20);
        tableDirect.getTableHeader().setResizingAllowed(false);
        tableDirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDirectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDirect);

        lbl_title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(7, 2, 2));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("اسم جدول");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Name)
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Name1)
                                .addGap(67, 67, 67))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Name1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbl_Name)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (txt_Name.getText().equals("")) {
                 View.Message a = new Message(this, true,  "الرجاء عم ترك مربع فارغ", MessageType.WARNING, 25);a.setVisible(true);
             
               // new rojerusan.RSNotifyAnimated("معلومات", "الرجاء عم ترك مربع فارغ", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
                return;
            }

            Conter_tables = new Funiction_Tables();
            Model.Model_Tables m = new Model_Tables(txt_Name.getText(), nameTable);
            boolean i = Conter_tables.add(m);
            if (i == true) {
                filltable();
                txt_Name.requestFocus();
                 View.Message a = new Message(this, true,   "تم اضافة بيانات بنجاح", MessageType.SUCCESS, 25);a.setVisible(true);
               
                //new rojerusan.RSNotifyAnimated("معلومات", "تم اضافة بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
            } else {
                txt_Name.requestFocus();
                         View.Message a = new Message(this, true,    "تم اضافة اسم قبل مرة ", MessageType.WARNING, 25);a.setVisible(true);
         
              //  new rojerusan.RSNotifyAnimated("معلومات", "تم اضافة اسم قبل مرة ", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);

            }
            txt_Name.setText("");
            txt_Name.requestFocus();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in  Funiction_Tables (View) go in btnAdd" + ex.getMessage());
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        try {
            if (txt_Id.getText() != null && txt_Name.getText().equals("")) {
                    View.Message a = new Message(this, true,    "الرجاء اختار اسم  للتعديل عليها", MessageType.WARNING, 25);a.setVisible(true);
                             JOptionPane.showMessageDialog(null, "الرجاء اختار اسم  للتعديل عليها");
       //         new rojerusan.RSNotifyAnimated("معلومات", "الرجاء اختار اسم  للتعديل عليها", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
                return;
            }
            Conter_tables = new Funiction_Tables();
            Model.Model_Tables m = new Model_Tables(Integer.valueOf(txt_Id.getText()), txt_Name.getText(), nameTable);
            txt_Id.setText("");
            txt_Name.setText("");
            Conter_tables.update(m);
            filltable();
            Disabled_btn();
            
              View.Message a = new Message(this, true,   "تم تعديل بيانات بنجاح", MessageType.SUCCESS, 25);a.setVisible(true);
                             
           // new rojerusan.RSNotifyAnimated("معلومات", "تم تعديل بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in  Funiction_Tables (View) go in btnUpdate" + ex.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed
        try {
            if (txt_Id.getText() != null && txt_Name.getText().equals("")) {
                   View.Message a = new Message(this, true,   "الرجاء اختار اسم للحذف بيانات من جدول", MessageType.WARNING, 25);a.setVisible(true);
                           
              // new rojerusan.RSNotifyAnimated("معلومات", "الرجاء اختار اسم للحذف بيانات من جدول", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
                return;
            }

            Conter_tables = new Funiction_Tables();
            Model.Model_Tables m = new Model_Tables(Integer.valueOf(txt_Id.getText()), nameTable);
            txt_Name.setText("");
            boolean i = Conter_tables.Delete(m);
            if (i == true) {
                filltable();
                txt_Name.setText("");
                View.Message a = new Message(this, true,   "تم حذف بيانات بنجاح", MessageType.SUCCESS, 25);a.setVisible(true);
            } else {
                filltable();
txt_Name.setText("");
                Disabled_btn();
                 View.Message a = new Message(this, true,   "لم يتم حذف بيانات", MessageType.WARNING, 25);a.setVisible(true);
           
               // new rojerusan.RSNotifyAnimated("معلومات", "لم يتم حذف بيانات", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in  Funiction_Tables (View) go in btnDelete" + ex.getMessage());
        }

    }//GEN-LAST:event_btnDel1ActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void tableDirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDirectMouseClicked
      
        try {
             int i = (int) tableDirect.getValueAt(tableDirect.getSelectedRow(), 1);
        String s = (String) tableDirect.getValueAt(tableDirect.getSelectedRow(), 0);
        txt_Id.setText(String.valueOf(i));
        txt_Name.setText(s);
        btnDel1.setEnabled(true);
        btnUpdate1.setEnabled(true); 
        } catch (Exception e) {
        }
      
    }//GEN-LAST:event_tableDirectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialShadow btnAdd;
    private RSMaterialComponent.RSButtonMaterialShadow btnDel1;
    private RSMaterialComponent.RSButtonMaterialShadow btnExit1;
    private RSMaterialComponent.RSButtonMaterialShadow btnUpdate1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name1;
    private javax.swing.JLabel lbl_title;
    private rojerusan.RSTableMetro tableDirect;
    private RSMaterialComponent.RSTextFieldMaterial txt_Id;
    private RSMaterialComponent.RSTextFieldMaterial txt_Name;
    // End of variables declaration//GEN-END:variables
}
