/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.C_employee;
import Control.Funiction_Tables;
import Control.generalcontrol;
import Model.Model_Tables;
import Model.general_Model;

import Model.m_registerno;
import Model.m_registerplace;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSPanelsSlider;


/**
 *
 * @author ahmad-soft
 */
public class frm_moves_and_secondment extends javax.swing.JDialog {


    
    public frm_moves_and_secondment(java.awt.Frame parent, boolean moda) {
          super(parent, moda);
        initComponents();
        txt_id_emp.setVisible(false);
        rSDateChooser1.setLocale(Locale.forLanguageTag("ar-SY"));

  
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        decisions = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSDateChooser1 = new newscomponents.RSDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_onus_id = new RSMaterialComponent.RSTextFieldMaterial();
        btn_nexit = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id_emp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id_onus = new javax.swing.JTextField();
        btn_Exit2 = new RSMaterialComponent.RSButtonMaterialShadow();
        moves_and_secondment = new javax.swing.JPanel();
        txt_name3 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_add1 = new RSMaterialComponent.RSButtonMaterialShadow();
        jScrollPane4 = new javax.swing.JScrollPane();
        List_Directorates1 = new javax.swing.JList<>();
        txt_name4 = new RSMaterialComponent.RSTextFieldMaterial();
        lbl_name9 = new javax.swing.JLabel();
        comb_names_emps2 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p6 = new javax.swing.JLabel();
        txt_name5 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p8 = new javax.swing.JLabel();
        N_type_of_doc_p9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comb_names_emps7 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p13 = new javax.swing.JLabel();
        comb_names_emps8 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p14 = new javax.swing.JLabel();
        comb_names_emps9 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p15 = new javax.swing.JLabel();
        N_type_of_doc_p16 = new javax.swing.JLabel();
        comb_names_emps10 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel3 = new javax.swing.JPanel();
        comb_names_emps11 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p17 = new javax.swing.JLabel();
        comb_names_emps12 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p18 = new javax.swing.JLabel();
        comb_names_emps13 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p19 = new javax.swing.JLabel();
        N_type_of_doc_p20 = new javax.swing.JLabel();
        comb_names_emps14 = new RSMaterialComponent.RSComboBoxMaterial();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        decisions.setBackground(new java.awt.Color(254, 254, 254));
        decisions.setName("decisions"); // NOI18N
        decisions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("رقم موظف");
        decisions.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, -1));

        rSDateChooser1.setBgColor(new java.awt.Color(185, 146, 79));
        rSDateChooser1.setLanguage(null);
        decisions.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 410, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel5.setText("واجهة اضافة قرار");
        decisions.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 300, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel6.setText("تاريخ القرار");
        decisions.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 210, -1));

        txt_onus_id.setForeground(new java.awt.Color(1, 1, 1));
        txt_onus_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_onus_id.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_onus_id.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_onus_id.setPlaceholder("");
        txt_onus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_onus_idActionPerformed(evt);
            }
        });
        decisions.add(txt_onus_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 410, -1));

        btn_nexit.setBackground(new java.awt.Color(185, 146, 79));
        btn_nexit.setText("التالي");
        btn_nexit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_nexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_nexit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_nexit.setEffectFocus(true);
        btn_nexit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_nexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nexitActionPerformed(evt);
            }
        });
        decisions.add(btn_nexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 120, 50));

        txt_id_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_empActionPerformed(evt);
            }
        });
        decisions.add(txt_id_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel7.setText("رقم القرار");
        decisions.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("رقم القرار");
        decisions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, -1));

        txt_id_onus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_onusActionPerformed(evt);
            }
        });
        decisions.add(txt_id_onus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 30));

        btn_Exit2.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit2.setText("خروج");
        btn_Exit2.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit2.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit2.setEffectFocus(true);
        btn_Exit2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit2ActionPerformed(evt);
            }
        });
        decisions.add(btn_Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 641, 120, 50));

        rSPanelsSlider1.add(decisions, "card2");

        moves_and_secondment.setBackground(new java.awt.Color(255, 255, 255));
        moves_and_secondment.setName("bonuses"); // NOI18N
        moves_and_secondment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name3.setForeground(new java.awt.Color(1, 1, 1));
        txt_name3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name3.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name3.setPlaceholder("");
        moves_and_secondment.add(txt_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, -1));

        N_type_of_doc_p3.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p3.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p3.setText("رقم قرار");
        moves_and_secondment.add(N_type_of_doc_p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel3.setText("واجهة اضافة قرار نقل الموظف");
        moves_and_secondment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        btn_add1.setBackground(new java.awt.Color(185, 146, 79));
        btn_add1.setText("خروج");
        btn_add1.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add1.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add1.setEffectFocus(true);
        btn_add1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        moves_and_secondment.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 107, 41));

        jScrollPane4.setViewportView(List_Directorates1);

        moves_and_secondment.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 720, 190));

        txt_name4.setForeground(new java.awt.Color(1, 1, 1));
        txt_name4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name4.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name4.setPlaceholder("");
        moves_and_secondment.add(txt_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 250, -1));

        lbl_name9.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        lbl_name9.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name9.setText("سبب النقل");
        moves_and_secondment.add(lbl_name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 90, -1));

        comb_names_emps2.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps2.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps2.setToolTipText("");
        comb_names_emps2.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps2ActionPerformed(evt);
            }
        });
        moves_and_secondment.add(comb_names_emps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 250, -1));

        N_type_of_doc_p6.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p6.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p6.setText("الراتب");
        N_type_of_doc_p6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moves_and_secondment.add(N_type_of_doc_p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, -1, 30));

        txt_name5.setForeground(new java.awt.Color(1, 1, 1));
        txt_name5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name5.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name5.setPlaceholder("");
        moves_and_secondment.add(txt_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 250, -1));

        N_type_of_doc_p8.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p8.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p8.setText(" اسم الموظف");
        moves_and_secondment.add(N_type_of_doc_p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        N_type_of_doc_p9.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p9.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p9.setText("نوع العملة");
        N_type_of_doc_p9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        moves_and_secondment.add(N_type_of_doc_p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "الى مكان العمل", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DIN Next LT Arabic", 1, 15))); // NOI18N

        comb_names_emps7.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps7.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps7.setToolTipText("");
        comb_names_emps7.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps7ActionPerformed(evt);
            }
        });

        N_type_of_doc_p13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p13.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p13.setText("الوزارة");

        comb_names_emps8.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps8.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps8.setToolTipText("");
        comb_names_emps8.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps8ActionPerformed(evt);
            }
        });

        N_type_of_doc_p14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p14.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p14.setText("المديرية");

        comb_names_emps9.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps9.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps9.setToolTipText("");
        comb_names_emps9.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps9ActionPerformed(evt);
            }
        });

        N_type_of_doc_p15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p15.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p15.setText("الدائرة");

        N_type_of_doc_p16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p16.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p16.setText("الشعبة");

        comb_names_emps10.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps10.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps10.setToolTipText("");
        comb_names_emps10.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(N_type_of_doc_p13)
                            .addComponent(N_type_of_doc_p15)
                            .addComponent(N_type_of_doc_p16)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(N_type_of_doc_p14)))
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(N_type_of_doc_p13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comb_names_emps8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(N_type_of_doc_p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(28, 28, 28))
        );

        moves_and_secondment.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 440, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "من مكان العمل", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DIN Next LT Arabic", 1, 15))); // NOI18N

        comb_names_emps11.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps11.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps11.setToolTipText("");
        comb_names_emps11.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps11ActionPerformed(evt);
            }
        });

        N_type_of_doc_p17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p17.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p17.setText("الوزارة");

        comb_names_emps12.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps12.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps12.setToolTipText("");
        comb_names_emps12.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps12ActionPerformed(evt);
            }
        });

        N_type_of_doc_p18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p18.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p18.setText("المديرية");

        comb_names_emps13.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps13.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps13.setToolTipText("");
        comb_names_emps13.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps13ActionPerformed(evt);
            }
        });

        N_type_of_doc_p19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p19.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p19.setText("الدائرة");

        N_type_of_doc_p20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p20.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p20.setText("الشعبة");

        comb_names_emps14.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps14.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps14.setToolTipText("");
        comb_names_emps14.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps14, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(N_type_of_doc_p17)
                            .addComponent(N_type_of_doc_p19)
                            .addComponent(N_type_of_doc_p20)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(N_type_of_doc_p18)))
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(N_type_of_doc_p17, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comb_names_emps12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(N_type_of_doc_p18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p19, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(28, 28, 28))
        );

        moves_and_secondment.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        rSPanelsSlider1.add(moves_and_secondment, "card3");

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, 700));

        rSPanelMaterial1.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 1, 1), 2, true));
        rSPanelMaterial1.setBgShade(new java.awt.Color(1, 1, 1));

        rSPanelMaterial2.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 146, 79), 2));
        rSPanelMaterial2.setForeground(new java.awt.Color(1, 1, 1));
        rSPanelMaterial2.setBgShade(new java.awt.Color(185, 146, 79));
        rSPanelMaterial2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_empActionPerformed

    private void txt_onus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_onus_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_onus_idActionPerformed

    private void btn_nexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nexitActionPerformed

        rSPanelsSlider1.slidPanel(20,moves_and_secondment , RSPanelsSlider.direct.Right);

    }//GEN-LAST:event_btn_nexitActionPerformed

    private void txt_id_onusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_onusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_onusActionPerformed

    private void btn_Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit2ActionPerformed
     this.dispose();
    }//GEN-LAST:event_btn_Exit2ActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void comb_names_emps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps2ActionPerformed

    private void comb_names_emps7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps7ActionPerformed

    private void comb_names_emps8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps8ActionPerformed

    private void comb_names_emps9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps9ActionPerformed

    private void comb_names_emps10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps10ActionPerformed

    private void comb_names_emps11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps11ActionPerformed

    private void comb_names_emps12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps12ActionPerformed

    private void comb_names_emps13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps13ActionPerformed

    private void comb_names_emps14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" cmb_districtook and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_moves_and_secondment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_moves_and_secondment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_moves_and_secondment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_moves_and_secondment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new families_members().setVisible(true);
           frm_moves_and_secondment dialog = new frm_moves_and_secondment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Model.Model_Tables> List_Directorates1;
    private javax.swing.JLabel N_type_of_doc_p13;
    private javax.swing.JLabel N_type_of_doc_p14;
    private javax.swing.JLabel N_type_of_doc_p15;
    private javax.swing.JLabel N_type_of_doc_p16;
    private javax.swing.JLabel N_type_of_doc_p17;
    private javax.swing.JLabel N_type_of_doc_p18;
    private javax.swing.JLabel N_type_of_doc_p19;
    private javax.swing.JLabel N_type_of_doc_p20;
    private javax.swing.JLabel N_type_of_doc_p3;
    private javax.swing.JLabel N_type_of_doc_p6;
    private javax.swing.JLabel N_type_of_doc_p8;
    private javax.swing.JLabel N_type_of_doc_p9;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit2;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add1;
    private RSMaterialComponent.RSButtonMaterialShadow btn_nexit;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps10;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps11;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps12;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps13;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps14;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps2;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps7;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps8;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps9;
    private javax.swing.JPanel decisions;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_name9;
    private javax.swing.JPanel moves_and_secondment;
    private newscomponents.RSDateChooser rSDateChooser1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextField txt_id_emp;
    private javax.swing.JTextField txt_id_onus;
    private RSMaterialComponent.RSTextFieldMaterial txt_name3;
    private RSMaterialComponent.RSTextFieldMaterial txt_name4;
    private RSMaterialComponent.RSTextFieldMaterial txt_name5;
    private RSMaterialComponent.RSTextFieldMaterial txt_onus_id;
    // End of variables declaration//GEN-END:variables
}
