/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.C_employee;
import Control.Funiction_Tables;
import Control.generalcontrol;
import Model.Model_Tables;
import Model.general_Model;

import Model.m_registerno;
import Model.m_registerplace;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSPanelsSlider;


/**
 *
 * @author ahmad-soft
 */
public class frm_financial_discount extends javax.swing.JDialog {


    
    public frm_financial_discount(java.awt.Frame parent, boolean moda) {
          super(parent, moda);
        initComponents();
        txt_id_emp.setVisible(false);
        rSDateChooser1.setLocale(Locale.forLanguageTag("ar-SY"));

  
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        decisions = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSDateChooser1 = new newscomponents.RSDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_onus_id = new RSMaterialComponent.RSTextFieldMaterial();
        btn_nexit = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id_emp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id_onus = new javax.swing.JTextField();
        btn_Exit2 = new RSMaterialComponent.RSButtonMaterialShadow();
        financial_discount = new javax.swing.JPanel();
        N_type_of_doc_p62 = new javax.swing.JLabel();
        txt_name24 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p63 = new javax.swing.JLabel();
        txt_name25 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p64 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_add8 = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id4 = new javax.swing.JTextField();
        rSCheckBoxMaterial5 = new RSMaterialComponent.RSCheckBoxMaterial();
        N_type_of_doc_p52 = new javax.swing.JLabel();
        txt_name27 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p54 = new javax.swing.JLabel();
        comb_names_emps6 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p65 = new javax.swing.JLabel();
        txt_name26 = new RSMaterialComponent.RSTextFieldMaterial();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        decisions.setBackground(new java.awt.Color(254, 254, 254));
        decisions.setName("decisions"); // NOI18N
        decisions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("رقم موظف");
        decisions.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, -1));

        rSDateChooser1.setBgColor(new java.awt.Color(185, 146, 79));
        rSDateChooser1.setLanguage(null);
        decisions.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 410, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel5.setText("واجهة اضافة قرار");
        decisions.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 300, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel6.setText("تاريخ القرار");
        decisions.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 210, -1));

        txt_onus_id.setForeground(new java.awt.Color(1, 1, 1));
        txt_onus_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_onus_id.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_onus_id.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_onus_id.setPlaceholder("");
        txt_onus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_onus_idActionPerformed(evt);
            }
        });
        decisions.add(txt_onus_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 410, -1));

        btn_nexit.setBackground(new java.awt.Color(185, 146, 79));
        btn_nexit.setText("التالي");
        btn_nexit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_nexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_nexit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_nexit.setEffectFocus(true);
        btn_nexit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_nexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nexitActionPerformed(evt);
            }
        });
        decisions.add(btn_nexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 120, 50));

        txt_id_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_empActionPerformed(evt);
            }
        });
        decisions.add(txt_id_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel7.setText("رقم القرار");
        decisions.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("رقم القرار");
        decisions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, -1));

        txt_id_onus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_onusActionPerformed(evt);
            }
        });
        decisions.add(txt_id_onus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 30));

        btn_Exit2.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit2.setText("خروج");
        btn_Exit2.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit2.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit2.setEffectFocus(true);
        btn_Exit2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit2ActionPerformed(evt);
            }
        });
        decisions.add(btn_Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 641, 120, 50));

        rSPanelsSlider1.add(decisions, "card2");

        financial_discount.setBackground(new java.awt.Color(255, 255, 255));
        financial_discount.setName("resignations"); // NOI18N

        N_type_of_doc_p62.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p62.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p62.setText("رقم قرار");

        txt_name24.setForeground(new java.awt.Color(1, 1, 1));
        txt_name24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name24.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name24.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name24.setPlaceholder("");

        N_type_of_doc_p63.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p63.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p63.setText(" اسم الموظف");

        txt_name25.setForeground(new java.awt.Color(1, 1, 1));
        txt_name25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name25.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name25.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name25.setPlaceholder("");

        N_type_of_doc_p64.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        N_type_of_doc_p64.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p64.setText("الموافقة على الطلب او عدم الموافقة");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel15.setText("واجهة اضافة قرار خصم");

        btn_add8.setBackground(new java.awt.Color(185, 146, 79));
        btn_add8.setText("خروج");
        btn_add8.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add8.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add8.setEffectFocus(true);
        btn_add8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add8ActionPerformed(evt);
            }
        });

        txt_id4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id4ActionPerformed(evt);
            }
        });

        rSCheckBoxMaterial5.setForeground(new java.awt.Color(185, 146, 79));
        rSCheckBoxMaterial5.setColorCheck(new java.awt.Color(185, 146, 79));
        rSCheckBoxMaterial5.setColorUnCheck(new java.awt.Color(185, 146, 79));
        rSCheckBoxMaterial5.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N

        N_type_of_doc_p52.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p52.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p52.setText("القيمة المالية للخصم");
        N_type_of_doc_p52.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_name27.setForeground(new java.awt.Color(1, 1, 1));
        txt_name27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name27.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name27.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name27.setPlaceholder("");

        N_type_of_doc_p54.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p54.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p54.setText("نوع العملة");
        N_type_of_doc_p54.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        comb_names_emps6.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps6.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps6.setToolTipText("");
        comb_names_emps6.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps6ActionPerformed(evt);
            }
        });

        N_type_of_doc_p65.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p65.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p65.setText("المدة الزمنية بالشهر");

        txt_name26.setForeground(new java.awt.Color(1, 1, 1));
        txt_name26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name26.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name26.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name26.setPlaceholder("");

        javax.swing.GroupLayout financial_discountLayout = new javax.swing.GroupLayout(financial_discount);
        financial_discount.setLayout(financial_discountLayout);
        financial_discountLayout.setHorizontalGroup(
            financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_discountLayout.createSequentialGroup()
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(financial_discountLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txt_id4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(financial_discountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_add8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(financial_discountLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_name24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comb_names_emps6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(financial_discountLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(rSCheckBoxMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N_type_of_doc_p62, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p63, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p65, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p64, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p52, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(N_type_of_doc_p54, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(financial_discountLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel15)))
                .addGap(340, 340, 340))
        );
        financial_discountLayout.setVerticalGroup(
            financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_discountLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_id4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel15)
                .addGap(61, 61, 61)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p62))
                .addGap(37, 37, 37)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p63))
                .addGap(37, 37, 37)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p65))
                .addGap(47, 47, 47)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N_type_of_doc_p64)
                    .addComponent(rSCheckBoxMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(financial_discountLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(N_type_of_doc_p52)))
                .addGap(37, 37, 37)
                .addGroup(financial_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_type_of_doc_p54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btn_add8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rSPanelsSlider1.add(financial_discount, "card3");

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, 700));

        rSPanelMaterial1.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 1, 1), 2, true));
        rSPanelMaterial1.setBgShade(new java.awt.Color(1, 1, 1));

        rSPanelMaterial2.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 146, 79), 2));
        rSPanelMaterial2.setForeground(new java.awt.Color(1, 1, 1));
        rSPanelMaterial2.setBgShade(new java.awt.Color(185, 146, 79));
        rSPanelMaterial2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_empActionPerformed

    private void txt_onus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_onus_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_onus_idActionPerformed

    private void btn_nexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nexitActionPerformed

     //   rSPanelsSlider1.slidPanel(20,moves_and_secondment , RSPanelsSlider.direct.Right);

    }//GEN-LAST:event_btn_nexitActionPerformed

    private void txt_id_onusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_onusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_onusActionPerformed

    private void btn_Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit2ActionPerformed
     this.dispose();
    }//GEN-LAST:event_btn_Exit2ActionPerformed

    private void btn_add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add8ActionPerformed

    private void txt_id4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id4ActionPerformed

    private void comb_names_emps6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" cmb_districtook and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_financial_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_financial_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_financial_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_financial_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new families_members().setVisible(true);
           frm_financial_discount dialog = new frm_financial_discount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N_type_of_doc_p52;
    private javax.swing.JLabel N_type_of_doc_p54;
    private javax.swing.JLabel N_type_of_doc_p62;
    private javax.swing.JLabel N_type_of_doc_p63;
    private javax.swing.JLabel N_type_of_doc_p64;
    private javax.swing.JLabel N_type_of_doc_p65;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit2;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add8;
    private RSMaterialComponent.RSButtonMaterialShadow btn_nexit;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps6;
    private javax.swing.JPanel decisions;
    private javax.swing.JPanel financial_discount;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial5;
    private newscomponents.RSDateChooser rSDateChooser1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextField txt_id4;
    private javax.swing.JTextField txt_id_emp;
    private javax.swing.JTextField txt_id_onus;
    private RSMaterialComponent.RSTextFieldMaterial txt_name24;
    private RSMaterialComponent.RSTextFieldMaterial txt_name25;
    private RSMaterialComponent.RSTextFieldMaterial txt_name26;
    private RSMaterialComponent.RSTextFieldMaterial txt_name27;
    private RSMaterialComponent.RSTextFieldMaterial txt_onus_id;
    // End of variables declaration//GEN-END:variables
}
