/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.C_employee;
import Control.Funiction_Tables;
import Control.generalcontrol;
import Model.Model_Tables;
import Model.general_Model;

import Model.m_registerno;
import Model.m_registerplace;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSPanelsSlider;


/**
 *
 * @author ahmad-soft
 */
public class frm_bonuses extends javax.swing.JDialog {


    
    public frm_bonuses(java.awt.Frame parent, boolean moda) {
          super(parent, moda);
        initComponents();
        txt_id_emp.setVisible(false);
        rSDateChooser1.setLocale(Locale.forLanguageTag("ar-SY"));

  
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        decisions = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSDateChooser1 = new newscomponents.RSDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_onus_id = new RSMaterialComponent.RSTextFieldMaterial();
        btn_nexit = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id_emp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id_onus = new javax.swing.JTextField();
        btn_Exit2 = new RSMaterialComponent.RSButtonMaterialShadow();
        bonuses = new javax.swing.JPanel();
        txt_name8 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_add3 = new RSMaterialComponent.RSButtonMaterialShadow();
        jScrollPane5 = new javax.swing.JScrollPane();
        List_Directorates2 = new javax.swing.JList<>();
        txt_name9 = new RSMaterialComponent.RSTextFieldMaterial();
        lbl_name10 = new javax.swing.JLabel();
        comb_names_emps3 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p11 = new javax.swing.JLabel();
        txt_name10 = new RSMaterialComponent.RSTextFieldMaterial();
        N_type_of_doc_p12 = new javax.swing.JLabel();
        N_type_of_doc_p21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        comb_names_emps21 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p28 = new javax.swing.JLabel();
        comb_names_emps22 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p29 = new javax.swing.JLabel();
        comb_names_emps27 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p30 = new javax.swing.JLabel();
        N_type_of_doc_p31 = new javax.swing.JLabel();
        comb_names_emps28 = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p56 = new javax.swing.JLabel();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        decisions.setBackground(new java.awt.Color(254, 254, 254));
        decisions.setName("decisions"); // NOI18N
        decisions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("رقم موظف");
        decisions.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, -1));

        rSDateChooser1.setBgColor(new java.awt.Color(185, 146, 79));
        rSDateChooser1.setLanguage(null);
        decisions.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 410, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel5.setText("واجهة اضافة قرار");
        decisions.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 300, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel6.setText("تاريخ القرار");
        decisions.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 210, -1));

        txt_onus_id.setForeground(new java.awt.Color(1, 1, 1));
        txt_onus_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_onus_id.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_onus_id.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_onus_id.setPlaceholder("");
        txt_onus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_onus_idActionPerformed(evt);
            }
        });
        decisions.add(txt_onus_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 410, -1));

        btn_nexit.setBackground(new java.awt.Color(185, 146, 79));
        btn_nexit.setText("التالي");
        btn_nexit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_nexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_nexit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_nexit.setEffectFocus(true);
        btn_nexit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_nexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nexitActionPerformed(evt);
            }
        });
        decisions.add(btn_nexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 120, 50));

        txt_id_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_empActionPerformed(evt);
            }
        });
        decisions.add(txt_id_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel7.setText("رقم القرار");
        decisions.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("رقم القرار");
        decisions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, -1));

        txt_id_onus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_onusActionPerformed(evt);
            }
        });
        decisions.add(txt_id_onus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 30));

        btn_Exit2.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit2.setText("خروج");
        btn_Exit2.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit2.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit2.setEffectFocus(true);
        btn_Exit2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit2ActionPerformed(evt);
            }
        });
        decisions.add(btn_Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 641, 120, 50));

        rSPanelsSlider1.add(decisions, "card2");

        bonuses.setBackground(new java.awt.Color(255, 255, 255));
        bonuses.setName("bonuses"); // NOI18N
        bonuses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name8.setForeground(new java.awt.Color(1, 1, 1));
        txt_name8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name8.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name8.setPlaceholder("");
        bonuses.add(txt_name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, -1));

        N_type_of_doc_p7.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p7.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p7.setText("مكان العمل");
        bonuses.add(N_type_of_doc_p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        jLabel10.setText("واجهة اضافة قرار مكافئة");
        bonuses.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btn_add3.setBackground(new java.awt.Color(185, 146, 79));
        btn_add3.setText("خروج");
        btn_add3.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add3.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add3.setEffectFocus(true);
        btn_add3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add3ActionPerformed(evt);
            }
        });
        bonuses.add(btn_add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 107, 41));

        jScrollPane5.setViewportView(List_Directorates2);

        bonuses.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 720, 190));

        txt_name9.setForeground(new java.awt.Color(1, 1, 1));
        txt_name9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name9.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name9.setPlaceholder("");
        bonuses.add(txt_name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 250, -1));

        lbl_name10.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        lbl_name10.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name10.setText("سبب المكافئة");
        bonuses.add(lbl_name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 110, -1));

        comb_names_emps3.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps3.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps3.setToolTipText("");
        comb_names_emps3.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps3ActionPerformed(evt);
            }
        });
        bonuses.add(comb_names_emps3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 250, -1));

        N_type_of_doc_p11.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p11.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p11.setText("القيمة مادية ");
        N_type_of_doc_p11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bonuses.add(N_type_of_doc_p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, 30));

        txt_name10.setForeground(new java.awt.Color(1, 1, 1));
        txt_name10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name10.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_name10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_name10.setPlaceholder("");
        bonuses.add(txt_name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 250, -1));

        N_type_of_doc_p12.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p12.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p12.setText(" اسم الموظف");
        bonuses.add(N_type_of_doc_p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        N_type_of_doc_p21.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p21.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p21.setText("نوع العملة");
        N_type_of_doc_p21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bonuses.add(N_type_of_doc_p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DIN Next LT Arabic", 1, 15))); // NOI18N

        comb_names_emps21.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps21.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps21.setToolTipText("");
        comb_names_emps21.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps21ActionPerformed(evt);
            }
        });

        N_type_of_doc_p28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p28.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p28.setText("الوزارة");

        comb_names_emps22.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps22.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps22.setToolTipText("");
        comb_names_emps22.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps22ActionPerformed(evt);
            }
        });

        N_type_of_doc_p29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p29.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p29.setText("المديرية");

        comb_names_emps27.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps27.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps27.setToolTipText("");
        comb_names_emps27.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps27ActionPerformed(evt);
            }
        });

        N_type_of_doc_p30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p30.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p30.setText("الدائرة");

        N_type_of_doc_p31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_type_of_doc_p31.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p31.setText("الشعبة");

        comb_names_emps28.setBackground(new java.awt.Color(254, 254, 254));
        comb_names_emps28.setForeground(new java.awt.Color(1, 1, 1));
        comb_names_emps28.setToolTipText("");
        comb_names_emps28.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_names_emps28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_names_emps28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_names_emps28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps28, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps27, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps22, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_names_emps21, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(N_type_of_doc_p28)
                            .addComponent(N_type_of_doc_p30)
                            .addComponent(N_type_of_doc_p31)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(N_type_of_doc_p29)))
                .addGap(55, 55, 55))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(N_type_of_doc_p28, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(comb_names_emps22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(N_type_of_doc_p29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p30, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_names_emps28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(N_type_of_doc_p31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(28, 28, 28))
        );

        bonuses.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        N_type_of_doc_p56.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N
        N_type_of_doc_p56.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p56.setText("رقم قرار");
        bonuses.add(N_type_of_doc_p56, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        rSPanelsSlider1.add(bonuses, "card3");

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, 700));

        rSPanelMaterial1.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 1, 1), 2, true));
        rSPanelMaterial1.setBgShade(new java.awt.Color(1, 1, 1));

        rSPanelMaterial2.setBackground(new java.awt.Color(254, 254, 254));
        rSPanelMaterial2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 146, 79), 2));
        rSPanelMaterial2.setForeground(new java.awt.Color(1, 1, 1));
        rSPanelMaterial2.setBgShade(new java.awt.Color(185, 146, 79));
        rSPanelMaterial2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_empActionPerformed

    private void txt_onus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_onus_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_onus_idActionPerformed

    private void btn_nexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nexitActionPerformed

     //   rSPanelsSlider1.slidPanel(20,moves_and_secondment , RSPanelsSlider.direct.Right);

    }//GEN-LAST:event_btn_nexitActionPerformed

    private void txt_id_onusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_onusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_onusActionPerformed

    private void btn_Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit2ActionPerformed
     this.dispose();
    }//GEN-LAST:event_btn_Exit2ActionPerformed

    private void btn_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add3ActionPerformed

    private void comb_names_emps3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps3ActionPerformed

    private void comb_names_emps21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps21ActionPerformed

    private void comb_names_emps22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps22ActionPerformed

    private void comb_names_emps27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps27ActionPerformed

    private void comb_names_emps28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_names_emps28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_names_emps28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" cmb_districtook and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_bonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_bonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_bonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_bonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new families_members().setVisible(true);
           frm_bonuses dialog = new frm_bonuses(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Model.Model_Tables> List_Directorates2;
    private javax.swing.JLabel N_type_of_doc_p11;
    private javax.swing.JLabel N_type_of_doc_p12;
    private javax.swing.JLabel N_type_of_doc_p21;
    private javax.swing.JLabel N_type_of_doc_p28;
    private javax.swing.JLabel N_type_of_doc_p29;
    private javax.swing.JLabel N_type_of_doc_p30;
    private javax.swing.JLabel N_type_of_doc_p31;
    private javax.swing.JLabel N_type_of_doc_p56;
    private javax.swing.JLabel N_type_of_doc_p7;
    private javax.swing.JPanel bonuses;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit2;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add3;
    private RSMaterialComponent.RSButtonMaterialShadow btn_nexit;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps21;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps22;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps27;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps28;
    private RSMaterialComponent.RSComboBoxMaterial comb_names_emps3;
    private javax.swing.JPanel decisions;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_name10;
    private newscomponents.RSDateChooser rSDateChooser1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextField txt_id_emp;
    private javax.swing.JTextField txt_id_onus;
    private RSMaterialComponent.RSTextFieldMaterial txt_name10;
    private RSMaterialComponent.RSTextFieldMaterial txt_name8;
    private RSMaterialComponent.RSTextFieldMaterial txt_name9;
    private RSMaterialComponent.RSTextFieldMaterial txt_onus_id;
    // End of variables declaration//GEN-END:variables
}
