/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.Funiction_Tables;
import Control.Lists_Meun;
import Control.control_user_admin;
import Model.Model_Tables;
import Model.getall;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;
import Model.m_User;
import java.util.ArrayList;

/**
 *
 * @author ahmad-soft
 */
public class frm_create_user extends javax.swing.JFrame {
public String  satat;

public boolean  b1 = false;
    /**
     * Creates new form ministry
     */
    public frm_create_user() {
        initComponents();
        fillCombobox();
    }
 
    Control.Funiction_Tables Conter_tables;

    public void fillCombobox() {

        Lists_Meun.Array_user_admin = Lists_Meun.Control_user.filltable("user_type");
        DefaultComboBoxModel model = (DefaultComboBoxModel)comb_Type.getModel() ;
        model.removeAllElements();
        model.addAll(Lists_Meun.Array_user_admin);

    }


    Model.m_User model = new m_User();
    Control.control_user_admin con = new control_user_admin();
public void claer_All(){
  txt_first_name.setText("");
  txt_middle_name.setText("");
  txt_last_name.setText("");
  txt_user_name.setText("");
  txt_password.setText("");
  comb_Type.setSelectedItem(null);  
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        materialShadowCircle1 = new efectos.MaterialShadowCircle();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_first_name = new RSMaterialComponent.RSTextFieldMaterial();
        lbl_name = new javax.swing.JLabel();
        btn_add = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_Exit = new RSMaterialComponent.RSButtonMaterialShadow();
        lbl_name1 = new javax.swing.JLabel();
        comb_Type = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p1 = new javax.swing.JLabel();
        txt_middle_name = new RSMaterialComponent.RSTextFieldMaterial();
        lbl_name2 = new javax.swing.JLabel();
        txt_last_name = new RSMaterialComponent.RSTextFieldMaterial();
        lbl_name3 = new javax.swing.JLabel();
        lbl_name4 = new javax.swing.JLabel();
        txt_user_name = new RSMaterialComponent.RSTextFieldMaterial();
        chk_password = new RSMaterialComponent.RSCheckBoxMaterial();
        txt_password = new RSMaterialComponent.RSPasswordMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 30)); // NOI18N
        jLabel1.setText("واجهة اضافة المستخدم");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        txt_first_name.setBackground(new java.awt.Color(254, 254, 254));
        txt_first_name.setForeground(new java.awt.Color(1, 1, 1));
        txt_first_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_first_name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_first_name.setDisabledTextColor(new java.awt.Color(0, 1, 1));
        txt_first_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_first_name.setPlaceholder("");
        txt_first_name.setSelectedTextColor(new java.awt.Color(254, 254, 254));
        txt_first_name.setSelectionColor(new java.awt.Color(142, 137, 137));
        jPanel2.add(txt_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 220, -1));

        lbl_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("اسم ");
        jPanel2.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        btn_add.setBackground(new java.awt.Color(185, 146, 79));
        btn_add.setText("اضافة");
        btn_add.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add.setEffectFocus(true);
        btn_add.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, 50));

        btn_Exit.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit.setText("خروج");
        btn_Exit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit.setEffectFocus(true);
        btn_Exit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 50));

        lbl_name1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name1.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name1.setText("كلمة المرور");
        jPanel2.add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        comb_Type.setBackground(new java.awt.Color(254, 254, 254));
        comb_Type.setForeground(new java.awt.Color(1, 1, 1));
        comb_Type.setToolTipText("");
        comb_Type.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_Type.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_TypeActionPerformed(evt);
            }
        });
        jPanel2.add(comb_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        N_type_of_doc_p1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        N_type_of_doc_p1.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N_type_of_doc_p1.setText("نوع مستخدم");
        jPanel2.add(N_type_of_doc_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 81, 52));

        txt_middle_name.setBackground(new java.awt.Color(254, 254, 254));
        txt_middle_name.setForeground(new java.awt.Color(1, 1, 1));
        txt_middle_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_middle_name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_middle_name.setDisabledTextColor(new java.awt.Color(0, 1, 1));
        txt_middle_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_middle_name.setPlaceholder("");
        txt_middle_name.setSelectedTextColor(new java.awt.Color(254, 254, 254));
        txt_middle_name.setSelectionColor(new java.awt.Color(142, 137, 137));
        jPanel2.add(txt_middle_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 220, -1));

        lbl_name2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name2.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name2.setText("اسم الاب");
        jPanel2.add(lbl_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        txt_last_name.setBackground(new java.awt.Color(254, 254, 254));
        txt_last_name.setForeground(new java.awt.Color(1, 1, 1));
        txt_last_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_last_name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_last_name.setDisabledTextColor(new java.awt.Color(0, 1, 1));
        txt_last_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_last_name.setPlaceholder("");
        txt_last_name.setSelectedTextColor(new java.awt.Color(254, 254, 254));
        txt_last_name.setSelectionColor(new java.awt.Color(142, 137, 137));
        jPanel2.add(txt_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 220, -1));

        lbl_name3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name3.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name3.setText("الكنية");
        jPanel2.add(lbl_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        lbl_name4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_name4.setForeground(new java.awt.Color(7, 2, 2));
        lbl_name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name4.setText("اسم مستخدم");
        jPanel2.add(lbl_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        txt_user_name.setBackground(new java.awt.Color(254, 254, 254));
        txt_user_name.setForeground(new java.awt.Color(1, 1, 1));
        txt_user_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user_name.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_user_name.setDisabledTextColor(new java.awt.Color(0, 1, 1));
        txt_user_name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_user_name.setPlaceholder("");
        txt_user_name.setSelectedTextColor(new java.awt.Color(254, 254, 254));
        txt_user_name.setSelectionColor(new java.awt.Color(142, 137, 137));
        jPanel2.add(txt_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 220, -1));

        chk_password.setForeground(new java.awt.Color(11, 10, 8));
        chk_password.setText("إظهار كلمة المرور");
        chk_password.setColorCheck(new java.awt.Color(185, 146, 79));
        chk_password.setColorUnCheck(new java.awt.Color(185, 146, 79));
        chk_password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chk_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_password.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chk_password.setIsEffectRipple(false);
        chk_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(chk_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, -1));

        txt_password.setBackground(new java.awt.Color(254, 254, 254));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(202, 77, 77)));
        txt_password.setForeground(new java.awt.Color(1, 1, 1));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setColorMaterial(new java.awt.Color(185, 146, 79));
        txt_password.setDisabledTextColor(new java.awt.Color(254, 254, 254));
        txt_password.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_password.setPhColor(new java.awt.Color(185, 146, 79));
        txt_password.setPlaceholder("");
        txt_password.setSelectionColor(new java.awt.Color(185, 146, 79));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 670, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        
        try {
            if (txt_first_name.getText().equals("")|| txt_middle_name.getText().equals("") || txt_last_name.getText().equals("")
                   || txt_user_name.getText().equals("") || txt_password.getText().equals("") || comb_Type.getSelectedItem()==null )  {
                              JOptionPane.showMessageDialog(null, "الرجاء عم ترك مربع فارغ");
             //   new rojerusan.RSNotifyAnimated("معلومات", "الرجاء عم ترك مربع فارغ", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
                return;
            }
   
             int id_type = ((Model_Tables) comb_Type.getSelectedItem()).getColumn_Id();
            model.setFirst_name(txt_first_name.getText());
            model.setMiddle_name(txt_middle_name.getText());
            model.setLast_name(txt_last_name.getText());
            model.setId_user_type(id_type);
            model.setPassword(txt_password.getText());
            model.setUser_name(txt_user_name.getText());  
            boolean i = con.add(model);
            if (i == true) {
                txt_first_name.requestFocus();
                claer_All();
                JOptionPane.showMessageDialog(null, "تم اضافة المستخدم بنجاح");
             //   new rojerusan.RSNotifyAnimated("معلومات", , 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
            } else {
                txt_first_name.requestFocus();

            }


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in   user (View) go in btnAdd" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void comb_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_TypeActionPerformed
        // TODO add your handling code here:
//        btn_Next.setEnabled(true);
    }//GEN-LAST:event_comb_TypeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void chk_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_passwordActionPerformed
      
        if(chk_password.isSelected()){
            txt_password.setEchoChar((char)0);
            
        }else{
            txt_password.setEchoChar(('*'));
        }
    }//GEN-LAST:event_chk_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_create_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N_type_of_doc_p1;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add;
    private javax.swing.ButtonGroup buttonGroup1;
    private RSMaterialComponent.RSCheckBoxMaterial chk_password;
    private RSMaterialComponent.RSComboBoxMaterial comb_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private efectos.MaterialShadowCircle materialShadowCircle1;
    private RSMaterialComponent.RSTextFieldMaterial txt_first_name;
    private RSMaterialComponent.RSTextFieldMaterial txt_last_name;
    private RSMaterialComponent.RSTextFieldMaterial txt_middle_name;
    private RSMaterialComponent.RSPasswordMaterial txt_password;
    private RSMaterialComponent.RSTextFieldMaterial txt_user_name;
    // End of variables declaration//GEN-END:variables

    
}
