/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Lists_Meun;

import Control.control_user_admin;
import Control.generalcontrol;
import Model.M_Directorates;
import Model.M_Ministry;
import Model.general_Model;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;
import Model.m_User;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmad-soft
 */
public class frm_permisiones_admin extends javax.swing.JFrame {

    public String satat;

    public boolean b1 = false;

    /**
     * Creates new form ministry
     */
    public frm_permisiones_admin() {
        initComponents();
        txt_id.setVisible(false);
        btn_del.setEnabled(false);
        fill_view_users();
        Emptied_Ministry_Directorates();
        fill_Ministry();
        fill_permisiones();
    }

    public void fill_permisiones() {
        
       
        Lists_Meun.array_view_permisiones_admins= Lists_Meun.view_permision_admins.view_permisiones_admins();
// Lists_Meun.array_permisiones = Lists_Meun.con_views_permisiones.view_permisiones();
       
        DefaultTableModel modle = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modle.setColumnIdentifiers(new Object[]{"رقم", "الاسم موظف", "الاسم الاب", " الكنية", "الاسم مديرية"});
        Object[] row = new Object[5];
        for (int i = 0; i <  Lists_Meun.array_view_permisiones_admins.size(); i++) {
            row[0] =  Lists_Meun.array_view_permisiones_admins.get(i).getID();
            row[1] =  Lists_Meun.array_view_permisiones_admins.get(i).getFirst_name();
            row[2] = Lists_Meun.array_view_permisiones_admins.get(i).getMiddle_name();
            row[3] =  Lists_Meun.array_view_permisiones_admins.get(i).getLast_name();
            row[4] =  Lists_Meun.array_view_permisiones_admins.get(i).getName();
            modle.addRow(row);
        }
        tableDirect.setModel(modle);
    }

    public void fill_view_users() {
Control.control_user_admin a = new control_user_admin();
ArrayList<m_User> c = new ArrayList();

c = a.view_admins();
 DefaultComboBoxModel model1 = (DefaultComboBoxModel) comb_admins.getModel();
        model1.removeAllElements();
model1.addAll(c);

    }

    public void fill_Ministry() {
        Lists_Meun.A_Ministry = Lists_Meun.C_Ministry.getAllRows();
        DefaultComboBoxModel model4 = (DefaultComboBoxModel) cmb_Ministry.getModel();
        model4.removeAllElements();
        model4.addAll(Lists_Meun.A_Ministry);
    }

    public void full_Direct() {
        int id_Ministry = ((M_Ministry) cmb_Ministry.getSelectedItem()).getId_Ministry();
        Lists_Meun.A_Direct = Lists_Meun.C_Direct.viewDirectorate(id_Ministry);
        List_Directorates.setModel(new DefaultComboBoxModel(Lists_Meun.A_Direct.toArray()));
    }

    public void Emptied_Ministry_Directorates() {
        cmb_Ministry.setModel(new DefaultComboBoxModel(new Integer[0]));
        List_Directorates.setModel(new DefaultComboBoxModel(new Integer[0]));

    }

    public void Emptied_users() {
        comb_admins.setModel(new DefaultComboBoxModel(new Integer[0]));
    }
    Control.generalcontrol control_general = new generalcontrol();
    Model.general_Model model_general = new general_Model();
    Model.m_User model = new m_User();
    Control.control_user_admin con = new control_user_admin();

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        materialShadowCircle1 = new efectos.MaterialShadowCircle();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_del = new RSMaterialComponent.RSButtonMaterialShadow();
        btn_Exit = new RSMaterialComponent.RSButtonMaterialShadow();
        comb_admins = new RSMaterialComponent.RSComboBoxMaterial();
        N_type_of_doc_p1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDirect = new rojerusan.RSTableMetro();
        N_type_of_doc_p2 = new javax.swing.JLabel();
        cmb_Ministry = new RSMaterialComponent.RSComboBoxMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_Directorates = new javax.swing.JList<>();
        btn_add1 = new RSMaterialComponent.RSButtonMaterialShadow();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 30)); // NOI18N
        jLabel1.setText("واجهة صلاحيات المدير ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btn_del.setBackground(new java.awt.Color(185, 146, 79));
        btn_del.setText("حذف");
        btn_del.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_del.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_del.setEffectFocus(true);
        btn_del.setEnabled(false);
        btn_del.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel2.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 90, 50));

        btn_Exit.setBackground(new java.awt.Color(185, 146, 79));
        btn_Exit.setText("خروج");
        btn_Exit.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Exit.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_Exit.setEffectFocus(true);
        btn_Exit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 50));

        comb_admins.setBackground(new java.awt.Color(254, 254, 254));
        comb_admins.setForeground(new java.awt.Color(1, 1, 1));
        comb_admins.setToolTipText("");
        comb_admins.setColorMaterial(new java.awt.Color(185, 146, 79));
        comb_admins.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comb_admins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_adminsActionPerformed(evt);
            }
        });
        jPanel2.add(comb_admins, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 220, -1));

        N_type_of_doc_p1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        N_type_of_doc_p1.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N_type_of_doc_p1.setText("اسم  المدير");
        jPanel2.add(N_type_of_doc_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 100, 52));

        tableDirect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الاسم حالة الإجتماعية", "الرقم حالة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDirect.setColorBackgoundHead(new java.awt.Color(185, 146, 79));
        tableDirect.setColorFilasBackgound2(new java.awt.Color(71, 60, 42));
        tableDirect.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tableDirect.setColorFilasForeground2(new java.awt.Color(253, 251, 251));
        tableDirect.setColorSelBackgound(new java.awt.Color(185, 146, 79));
        tableDirect.setFont(new java.awt.Font("Arial CE", 1, 15)); // NOI18N
        tableDirect.setFuenteFilas(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableDirect.setFuenteHead(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tableDirect.setRowHeight(20);
        tableDirect.getTableHeader().setResizingAllowed(false);
        tableDirect.getTableHeader().setReorderingAllowed(false);
        tableDirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDirectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDirect);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 480, 270));

        N_type_of_doc_p2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        N_type_of_doc_p2.setForeground(new java.awt.Color(7, 2, 2));
        N_type_of_doc_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N_type_of_doc_p2.setText("اسم الوزارة");
        jPanel2.add(N_type_of_doc_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 100, 52));

        cmb_Ministry.setBackground(new java.awt.Color(254, 254, 254));
        cmb_Ministry.setForeground(new java.awt.Color(1, 1, 1));
        cmb_Ministry.setToolTipText("");
        cmb_Ministry.setColorMaterial(new java.awt.Color(185, 146, 79));
        cmb_Ministry.setEnabled(false);
        cmb_Ministry.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmb_Ministry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_MinistryActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_Ministry, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 220, -1));

        jScrollPane2.setViewportView(List_Directorates);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 310, 240));

        btn_add1.setBackground(new java.awt.Color(185, 146, 79));
        btn_add1.setText("اضافة");
        btn_add1.setBackgroundHover(new java.awt.Color(117, 101, 75));
        btn_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add1.setEffectButton(RSMaterialComponent.RSButtonMaterialShadow.EFFECTBUTTON.RAISED);
        btn_add1.setEffectFocus(true);
        btn_add1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 90, 50));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 850, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tableDirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDirectMouseClicked
        int i = (int) tableDirect.getValueAt(tableDirect.getSelectedRow(), 0);
        txt_id.setText(String.valueOf(i));
        btn_del.setEnabled(true);
    }//GEN-LAST:event_tableDirectMouseClicked

    private void comb_adminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_adminsActionPerformed
cmb_Ministry.setEnabled(true);
    }//GEN-LAST:event_comb_adminsActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

      this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        try {
            if ( txt_id.getText().equals("")) {
                                              JOptionPane.showMessageDialog(null, "الرجاء اختار الاسم مستخدم  للحذف عليها");
                //new rojerusan.RSNotifyAnimated("معلومات", "الرجاء اختار الاسم مستخدم  للحذف عليها", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
                return;
            }
            model_general.setId(Integer.valueOf(txt_id.getText()));
            control_general.delete(model_general, "permisione_admins");

            fill_permisiones();
            btn_del.setEnabled(false);
                  JOptionPane.showMessageDialog(null, "تم حذف بيانات بنجاح");
        //    new rojerusan.RSNotifyAnimated("معلومات", "تم حذف بيانات بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error  go -> btnDeleteMouseClicked in frm_permisiones" + ex.getMessage());
        }

    }//GEN-LAST:event_btn_delActionPerformed

    private void cmb_MinistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_MinistryActionPerformed

        full_Direct();
        List_Directorates.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_MinistryActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed

        try {
            if (comb_admins.getSelectedItem() == null || cmb_Ministry.getSelectedItem() == null || List_Directorates.getSelectedValue() == null) {
                                              JOptionPane.showMessageDialog(null, "الرجاء عم ترك مربع فارغ");
           //     new rojerusan.RSNotifyAnimated("معلومات", "الرجاء عم ترك مربع فارغ", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.WARNING).setVisible(true);
                return;
            }

            int[] selected = List_Directorates.getSelectedIndices();
            for (int i = 0; i < selected.length; i++) {
                int id_Directorate = ((M_Directorates) List_Directorates.getModel().getElementAt(selected[i])).getID();
                int id_users1 = ((m_User) comb_admins.getSelectedItem()).getID();
                model.setId_work_place(id_Directorate);
                model.setID(id_users1);
                con.add_permisions_admins(model);

            }
                                          JOptionPane.showMessageDialog(null, "تم اضافة  صلاحية بنجاح");
           // new rojerusan.RSNotifyAnimated("معلومات", "تم اضافة  صلاحية بنجاح", 5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.RightLeft, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
            fill_permisiones();
            Emptied_users();
            Emptied_Ministry_Directorates();
            fill_view_users();
//            full_Direct();
            fill_Ministry();
       
            List_Directorates.setEnabled(false);
            cmb_Ministry.setEnabled(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error in   permisipmes (View) go in btnAdd" + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_permisiones_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_permisiones_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_permisiones_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_permisiones_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_permisiones_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Model.M_Directorates> List_Directorates;
    private javax.swing.JLabel N_type_of_doc_p1;
    private javax.swing.JLabel N_type_of_doc_p2;
    private RSMaterialComponent.RSButtonMaterialShadow btn_Exit;
    private RSMaterialComponent.RSButtonMaterialShadow btn_add1;
    private RSMaterialComponent.RSButtonMaterialShadow btn_del;
    private javax.swing.ButtonGroup buttonGroup1;
    private RSMaterialComponent.RSComboBoxMaterial cmb_Ministry;
    private RSMaterialComponent.RSComboBoxMaterial comb_admins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private efectos.MaterialShadowCircle materialShadowCircle1;
    private rojerusan.RSTableMetro tableDirect;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

}
